sudo: false
branches:
  only:
    - master

language: ruby
cache: bundler
dist: trusty
rvm: 2.3.3

before_install:
- gem update --system
- gem update bundler
- gem --version

script:
  - bundle exec rake

env:
  matrix:
  - TRAVIS_CHEF_VERSION="~> 12.0" # latest 12.x.y
  - TRAVIS_CHEF_VERSION="~> 13.0" # latest 13.x.y
  - TRAVIS_CHEF_VERSION="branch:v12.19.36" # chef-server stable
